# Generated by Django 6.0.2 on 2026-03-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Acme Corporation', max_length=255, verbose_name='Business Name')),
                ('ai_type', models.CharField(choices=[('website_based_ai', 'Website-Based AI')], default='website_based_ai', max_length=50, verbose_name='AI Type')),
                ('website_url', models.URLField(help_text='https://www.yourbusiness.com', verbose_name='Website URL')),
                ('description', models.TextField(help_text='Describe your primary business focus...', verbose_name='Description')),
            ],
        ),
    ]
