# Generated by Django 6.0.2 on 2026-03-28 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_business_ai_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_chunk', models.TextField(verbose_name='Text Chunk')),
                ('embedding', models.JSONField(verbose_name='Embedding Vector')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='business.business')),
            ],
        ),
    ]
