# Generated by Django 6.0.2 on 2026-03-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessembedding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessEmbedding',
        ),
    ]
