# Generated by Django 6.0.2 on 2026-03-28 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_delete_businessembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_embedding', models.JSONField(verbose_name='Vector Data')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Text Chunk')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_data', to='business.business')),
            ],
        ),
    ]
