# Generated by Django 6.0.2 on 2026-03-28 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_businessembedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessembedding',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='businessembedding',
            name='vector_embedding',
        ),
        migrations.AddField(
            model_name='businessembedding',
            name='embeddings_data',
            field=models.JSONField(default=list, verbose_name='All Embeddings Data'),
        ),
        migrations.AlterField(
            model_name='businessembedding',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector_data', to='business.business'),
        ),
    ]
