# Generated by Django 6.0.2 on 2026-03-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='ai_type',
        ),
    ]
