# Generated by Django 6.0.2 on 2026-03-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
