# Generated by Django 6.0.2 on 2026-03-29 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='domain',
            field=models.CharField(choices=[('Health & Wellness', 'Health & Wellness'), ('Personal Care & Lifestyle', 'Personal Care & Lifestyle'), ('Professional Services', 'Professional Services'), ('Hospitality & Leisure', 'Hospitality & Leisure'), ('Education & Training', 'Education & Training'), ('Services & Maintenance', 'Services & Maintenance')], default='Services', max_length=100),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(default='confirmed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.business')),
            ],
        ),
    ]
