# Generated by Django 5.2.12 on 2026-03-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_business_domain_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_name',
            field=models.CharField(default='General Service', max_length=255),
        ),
    ]
