# Generated by Django 6.0.2 on 2026-04-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_populate_rooftop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='domain',
        ),
    ]
