# Generated by Django 6.0.2 on 2026-04-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
