# Generated by Django 6.0.2 on 2026-04-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_businessservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='external_uuid',
            field=models.UUIDField(blank=True, help_text='ID from external system', null=True, unique=True),
        ),
    ]
