# Generated by Django 6.0.2 on 2026-04-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_business_external_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessservice',
            name='biz_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='biz_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='biz_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='biz_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='biz_logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='biz_phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='biz_service_name',
            field=models.CharField(blank=True, help_text='Service name from businesses table', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='biz_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='biz_zip_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='max_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='service_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
