# Generated by Django 6.0.2 on 2026-04-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_businessservice_biz_address_businessservice_biz_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
